globalThis.process ??= {}; globalThis.process.env ??= {};
import { c as createComponent, r as renderComponent, a as renderTemplate, m as maybeRenderHead } from '../../chunks/astro/server_BA1YRW7y.mjs';
import { $ as $$BlogPost } from '../../chunks/BlogPost_DrskGsOj.mjs';
export { r as renderers } from '../../chunks/_@astro-renderers_CIWobTvY.mjs';

const $$12HowToGetPostTitleInWordpress = createComponent(($$result, $$props, $$slots) => {
  const title = "How to get post title in WordPress?";
  const description = "Mastering WordPress Data: How to Retrieve Custom Titles from SEO Plugins As a senior developer, I often encounter scenarios where we need to extract specific...";
  const date = "2026-08-10";
  return renderTemplate`${renderComponent($$result, "BlogPost", $$BlogPost, { "title": title, "description": description, "date": date }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<h1>Mastering WordPress Data: How to Retrieve Custom Titles from SEO Plugins</h1> <p>As a senior developer, I often encounter scenarios where we need to extract specific data from a WordPress installation, especially when third-party plugins are involved. The challenge you've described—needing the title generated by an SEO plugin (like All in one SEO Pack) rather than the default WordPress post title—is a very common requirement.</p> <p>You have correctly identified that simply using <code>get_the_title()</code> will only retrieve the standard post title, ignoring the optimized title managed by your SEO plugin. To solve this, we need to shift our focus from the default post object to accessing the custom meta data stored by the plugin in the WordPress database.</p> <p>This post will guide you through the developer-centric approach to retrieving the specific title required for your translation script, ensuring you get the exact text needed for conversion.</p> <h2>Understanding WordPress Data Retrieval</h2> <p>In WordPress, most plugin-specific information, such as SEO titles, meta descriptions, or custom settings, is stored in the <code>wp_postmeta</code> table. To access this data, we must use WordPress's built-in functions designed for retrieving post metadata, specifically <code>get_post_meta()</code>.</p> <p>When a plugin saves a value to the database, it typically associates that value with the post ID. We need to first ensure we are targeting the correct Post ID and then fetch the specific meta key used by the SEO pack.</p> <h2>Modifying Your Conversion Function</h2> <p>Your existing function for Arabic-to-English conversion is solid; the logic using <code>preg_replace</code> is effective for handling complex character mapping. The adjustment needed is in the data source within the function itself. Instead of relying on standard theme functions, we will use WordPress APIs to pull the SEO title.</p> <p>Here is how you can refactor your code to fetch the title saved by the All in one SEO Pack plugin:</p> <pre><code class="language-php">function arb2en_title($post_id)
  &#123;
      // 1. Define the meta key used by AIOSEO (you must verify this key)
      $seo_title_key = '_yoast_wpseo_title'; // This is a common Yoast SEO key, check your specific plugin documentation!
  
      // 2. Retrieve the specific title from post meta using the Post ID
      if ( ! $post_id ) &#123;
          return '';
      &#125;
      $text = get_post_meta($post_id, $seo_title_key, true);
  
      // Check if we successfully retrieved a title
      if ( empty($text) ) &#123;
          return '';
      &#125;
  
      // 3. Perform the Arabic to English conversion logic
      $arb_en_map = array(
             'د' =&gt; ']',
             'ج' =&gt; '[',
             'ح' =&gt; 'p',
             'خ' =&gt; 'o',
             'ه' =&gt; 'i',
             'ع' =&gt; 'u',
             'غ' =&gt; 'y',
             'ف' =&gt; 't',
             'ق' =&gt; 'r',
             'ث' =&gt; 'e',
             'ص' =&gt; 'w',
             'ض' =&gt; 'q',
             'ش' =&gt; 'a',
             'س' =&gt; 's',
             'ي' =&gt; 'd',
             'ب' =&gt; 'f',
             'ل' =&gt; 'g',
             'ا' =&gt; 'h',
             'ت' =&gt; 'j',
             'ن' =&gt; 'k',
             'م' =&gt; 'l',
             'ك' =&gt; ';',
             'ط' =&gt; '\\'',
             'ظ' =&gt; '/',
             'ز' =&gt; '.',
             'و' =&gt; ',',
             'ة' =&gt; 'm',
             'ى' =&gt; 'n',
             'لا' =&gt; 'b',
             'ر' =&gt; 'v',
             'ؤ' =&gt; 'c',
             'ء' =&gt; 'x',
             'ئ' =&gt; 'z',
             'إ' =&gt; 'Y',
             'لإ' =&gt; 'T',
             'لأ' =&gt; 'G',
             'أ' =&gt; 'H',
             'لآ' =&gt; 'B',
             'آ' =&gt; 'N'
      );
  
      foreach($arb_en_map as $key =&gt; $value)
      &#123;
          $text = preg_replace(&quot;/$key/&quot;, $value, $text);
      &#125;
  
      return htmlentities($text);
  &#125;
  </code></pre> <h3>Key Takeaways for Robust Development</h3> <p>Notice the crucial change: instead of passing a post number (or relying on <code>$post</code>), the function now requires the <code>$post_id</code> and uses <code>get_post_meta()</code>. This is the standard, robust way to interact with custom plugin data in WordPress. When building complex systems, like those you might encounter when architecting solutions similar to what is discussed in modern frameworks like Laravel, relying on well-defined data access methods rather than direct string manipulation ensures your code remains maintainable and scalable.</p> <h2>Conclusion</h2> <p>To successfully get the title from a specific SEO plugin within WordPress, you must bypass standard theme functions and delve into the database structure using <code>get_post_meta()</code>. By correctly identifying the unique meta key used by the All in one SEO Pack—and ensuring your function operates on the correct Post ID—you can reliably extract the data needed for your Arabic-to-English conversion. This approach ensures that your custom scripts interact cleanly with the dynamic content managed by your plugins, leading to accurate and reliable results every time.</p> ` })}`;
}, "/home/stefan/Projects/laravelseo.com/src/pages/blog/12-how-to-get-post-title-in-wordpress.astro", void 0);

const $$file = "/home/stefan/Projects/laravelseo.com/src/pages/blog/12-how-to-get-post-title-in-wordpress.astro";
const $$url = "/blog/12-how-to-get-post-title-in-wordpress";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  default: $$12HowToGetPostTitleInWordpress,
  file: $$file,
  url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
